import React from "react";

import { Metadata } from "next";
import { USER_ROLE } from "@/constants/role";
import { RootDashboard } from "@/components/dashboard/RootDashboard";

export const metadata: Metadata = {
  title: "Blogs | blogPlex",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <RootDashboard>{children}</RootDashboard>
    </div>
  );
};

export default DashboardLayout;
